version: '3'
services:
  python-app:
    build:
      context: .
      dockerfile: Python.Dockerfile
    container_name: concurso_bb
    ports:
      - "5000:80"
    restart: always
    # fazer o container rodar em background
    command: ["python", "app.py"]

  java-app:
    build:
      context: .
      dockerfile: Java.Dockerfile
    container_name: java-container
    ports:
      - "8080:8080"
    restart: always
    # fazer o container rodar em background
    command: ["java", "-jar", "app.jar"]

  postgres:
    build:
      context: .
      dockerfile: Postgres.Dockerfile
    container_name: postgres-container
    ports:
      - "5432:5432"
    restart: always
